wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.17.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1720290787
    t:
      1:
      - 1
      - 5
      - 30
      - 53
      - 55
      2:
      - 1
      - 5
      - 30
      - 53
      - 55
      3:
      - 13
      - 23
      - 34
      4: 3.9.19
      5: 0.17.4
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
